app:
  name: notification-service
  log_level: info

http:
  host: 0.0.0.0
  port: 8080

grpc:
  host: 0.0.0.0
  port: 9090

postgres:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  db: notifications
  ssl_mode: disable

kafka:
  brokers:
    - localhost:9094
  topic: notifications
  group_id: notification-consumer

redis:
  addr: localhost:6379

otlp:
  endpoint: localhost:4317

telegram:
  token: ""
