// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Notification struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Title     string
	Text      string
	Channel   string
	Status    string
	SentAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID         pgtype.UUID
	Name       string
	Surname    pgtype.Text
	TelegramID int64
	CreatedAt  pgtype.Timestamptz
}
