// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNotification = `-- name: CreateNotification :exec
INSERT INTO notifications (id, user_id, title, text, channel, status, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateNotificationParams struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Title     string
	Text      string
	Channel   string
	Status    string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) error {
	_, err := q.db.Exec(ctx, createNotification,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Text,
		arg.Channel,
		arg.Status,
		arg.CreatedAt,
	)
	return err
}

const deleteNotification = `-- name: DeleteNotification :exec
DELETE FROM notifications WHERE id = $1
`

func (q *Queries) DeleteNotification(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteNotification, id)
	return err
}

const getNotificationByID = `-- name: GetNotificationByID :one
SELECT id, user_id, title, text, channel, status, sent_at, created_at FROM notifications WHERE id = $1
`

func (q *Queries) GetNotificationByID(ctx context.Context, id pgtype.UUID) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotificationByID, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Text,
		&i.Channel,
		&i.Status,
		&i.SentAt,
		&i.CreatedAt,
	)
	return i, err
}

const listFailedNotifications = `-- name: ListFailedNotifications :many
SELECT id, user_id, title, text, channel, status, sent_at, created_at FROM notifications
WHERE status = 'failed' AND created_at >= now() - $2::interval
ORDER BY created_at ASC
LIMIT $1
`

type ListFailedNotificationsParams struct {
	Limit int32
	Since pgtype.Interval
}

func (q *Queries) ListFailedNotifications(ctx context.Context, arg ListFailedNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listFailedNotifications, arg.Limit, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Text,
			&i.Channel,
			&i.Status,
			&i.SentAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationsByUserID = `-- name: ListNotificationsByUserID :many
SELECT id, user_id, title, text, channel, status, sent_at, created_at FROM notifications
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListNotificationsByUserIDParams struct {
	UserID pgtype.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListNotificationsByUserID(ctx context.Context, arg ListNotificationsByUserIDParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Text,
			&i.Channel,
			&i.Status,
			&i.SentAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNotificationStatus = `-- name: UpdateNotificationStatus :exec
UPDATE notifications SET status = $1, sent_at = $2 WHERE id = $3
`

type UpdateNotificationStatusParams struct {
	Status string
	SentAt pgtype.Timestamptz
	ID     pgtype.UUID
}

func (q *Queries) UpdateNotificationStatus(ctx context.Context, arg UpdateNotificationStatusParams) error {
	_, err := q.db.Exec(ctx, updateNotificationStatus, arg.Status, arg.SentAt, arg.ID)
	return err
}
